import React,{useEffect,useState} from 'react';
import {getStoredPrayerData,getNextPrayer,calculateFromCoordinates,getPrayerMethod,setPrayerMethod} from '../services/prayerService';
import {getCurrentLocation} from '../services/locationPrayerService';
export default function Prayer({setPage}){
 const [data,setData]=useState(getStoredPrayerData()); const [busy,setBusy]=useState(false); const [method,setMethod]=useState(getPrayerMethod()); const [,tick]=useState(0);
 useEffect(()=>{const id=setInterval(()=>tick(x=>x+1),30000); getCurrentLocation().then(x=>x&&setData(x)).catch(()=>{}); return()=>clearInterval(id)},[]);
 const next=getNextPrayer(data), names={Fajr:'الفجر',Dhuhr:'الظهر',Asr:'العصر',Maghrib:'المغرب',Isha:'العشاء'};
 const refresh=async()=>{setBusy(true);try{const loc=await getCurrentLocation(true);if(loc){const x=await calculateFromCoordinates(loc.latitude,loc.longitude,method);setData(x)}}finally{setBusy(false)}};
 return <section className="page fade-in"><div className="page-title"><span>الصلاة</span><small>{data.location} · {data.source==='cache'?'آخر بيانات محفوظة':''}</small></div><div className="prayer-hero"><span>الصلاة القادمة</span><strong>{next?.name||'لا توجد بيانات'}</strong><b>{next?.time||'--:--'}</b><small>{next?.remaining||'حدد موقعك لتحديث المواقيت'}</small></div><div className="prayer-list">{Object.entries(data.times||{}).map(([k,t])=><div className={'prayer-row '+(next?.key===k?'active':'')} key={k}><span>{names[k]}</span><strong>{t||'--:--'}</strong><small>{next?.key===k?'القادمة':''}</small></div>)}</div><div className="settings-card"><label>طريقة الحساب <select value={method} onChange={e=>{const v=Number(e.target.value);setMethod(v);setPrayerMethod(v)}}><option value="3">رابطة العالم الإسلامي</option><option value="2">ISNA</option><option value="4">أم القرى</option><option value="5">الهيئة المصرية</option></select></label></div><div className="button-row"><button className="secondary" disabled={busy} onClick={refresh}>{busy?'جاري التحديث…':'تحديث الموقع والمواقيت'}</button><button className="secondary" onClick={()=>setPage('AdhanSettings')}>إعدادات الأذان</button></div></section>;
}
