plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.noorpromax'
    compileSdk 35

    defaultConfig {
        applicationId 'com.noorpromax'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    kotlinOptions {
        jvmTarget = '21'
    }

    buildFeatures {
        buildConfig true
    }
}

dependencies {
    implementation project(':capacitor-android')
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.startapp:inapp-sdk:5.1.0'
}
